In [ ]:
import pandas as pd

df = pd.read_csv("dataset/synthetic_logs.csv")
df.head(3)

,timestamp,source,log_message,target_label,complexity
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,bert
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,bert
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,bert
3,2025-07-12 00:24:16,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,bert
4,2025-06-02 18:25:23,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,bert

In [7]:
filtered_df = df[df["target_label"] == "Error"]
filtered_df.head()

,timestamp,source,log_message,target_label,complexity
6,3/1/2025 19:14,ModernHR,Shard 6 replication task ended in failure,Error,bert
10,8/9/2025 18:58,ModernCRM,Email server encountered a sending fault,Error,bert
45,5/22/2025 3:17,ThirdPartyAPI,Data replication task for shard 14 did not com...,Error,bert
51,8/19/2025 5:58,ThirdPartyAPI,Server 4 restarted without warning during data...,Error,bert
55,6/18/2025 11:21,AnalyticsEngine,Server 34 crashed unexpectedly while syncing data,Error,bert

In [8]:
filtered_df = df[df["source"] == "ModernCRM"]
filtered_df.head()

,timestamp,source,log_message,target_label,complexity
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,bert
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,bert
10,8/9/2025 18:58,ModernCRM,Email server encountered a sending fault,Error,bert
15,5/1/2025 9:41,ModernCRM,Backup completed successfully.,System Notification,regex
17,2025-01-27 12:39:05,ModernCRM,nova.osapi_compute.wsgi.server [req-5f1c2027-e...,HTTP Status,bert

In [ ]:
df.source.unique()

<StringArray>
[      'ModernCRM', 'AnalyticsEngine',        'ModernHR',   'BillingSystem',
   'ThirdPartyAPI',       'LegacyCRM']
Length: 6, dtype: str

In [3]:
df["target_label"].unique()

<StringArray>
[        'HTTP Status',      'Critical Error',      'Security Alert',
               'Error', 'System Notification',      'Resource Usage',
         'User Action',      'Workflow Error', 'Deprecation Warning']
Length: 9, dtype: str

In [4]:
df["target_label"].value_counts()

target_label
HTTP Status            1017
Security Alert          371
System Notification     356
Error                   177
Resource Usage          177
Critical Error          161
User Action             144
Workflow Error            4
Deprecation Warning       3
Name: count, dtype: int64