In [2]:
import pandas as pd

df = pd.read_csv("dataset/synthetic_logs.csv")
df.head(3)

,timestamp,source,log_message,target_label,complexity
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,bert
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,bert
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,bert

In [3]:
filtered_df = df[df["target_label"] == "Error"]
filtered_df.head()

,timestamp,source,log_message,target_label,complexity
6,3/1/2025 19:14,ModernHR,Shard 6 replication task ended in failure,Error,bert
10,8/9/2025 18:58,ModernCRM,Email server encountered a sending fault,Error,bert
45,5/22/2025 3:17,ThirdPartyAPI,Data replication task for shard 14 did not com...,Error,bert
51,8/19/2025 5:58,ThirdPartyAPI,Server 4 restarted without warning during data...,Error,bert
55,6/18/2025 11:21,AnalyticsEngine,Server 34 crashed unexpectedly while syncing data,Error,bert

In [4]:
filtered_df = df[df["source"] == "ModernCRM"]
filtered_df.head()

,timestamp,source,log_message,target_label,complexity
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,bert
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,bert
10,8/9/2025 18:58,ModernCRM,Email server encountered a sending fault,Error,bert
15,5/1/2025 9:41,ModernCRM,Backup completed successfully.,System Notification,regex
17,2025-01-27 12:39:05,ModernCRM,nova.osapi_compute.wsgi.server [req-5f1c2027-e...,HTTP Status,bert

In [5]:
df.source.unique()

<StringArray>
[      'ModernCRM', 'AnalyticsEngine',        'ModernHR',   'BillingSystem',
   'ThirdPartyAPI',       'LegacyCRM']
Length: 6, dtype: str

In [6]:
df["target_label"].unique()

<StringArray>
[        'HTTP Status',      'Critical Error',      'Security Alert',
               'Error', 'System Notification',      'Resource Usage',
         'User Action',      'Workflow Error', 'Deprecation Warning']
Length: 9, dtype: str

In [7]:
df["target_label"].value_counts()

target_label
HTTP Status            1017
Security Alert          371
System Notification     356
Error                   177
Resource Usage          177
Critical Error          161
User Action             144
Workflow Error            4
Deprecation Warning       3
Name: count, dtype: int64

In [8]:
from sentence_transformers import SentenceTransformer
from sklearn.cluster import DBSCAN

# Generate embeddings for log_message column
model = SentenceTransformer('all-MiniLM-L6-v2')
embeddings = model.encode(df['log_message'].tolist())

embeddings[:2]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

array([[-1.02939643e-01,  3.35459560e-02, -2.20260546e-02,
         1.55099435e-03, -9.86917224e-03, -1.78956345e-01,
        -6.34410158e-02, -6.01762161e-02,  2.81108748e-02,
         5.99619932e-02, -1.72618870e-02,  1.43367937e-03,
        -1.49560049e-01,  3.15283053e-03, -5.66030554e-02,
         2.71685459e-02, -1.49890343e-02, -3.54037508e-02,
        -3.62936072e-02, -1.45410430e-02, -5.61489770e-03,
         8.75538886e-02,  4.55121212e-02,  2.50963587e-02,
         1.00187939e-02,  1.24266772e-02, -1.39923558e-01,
         7.68696293e-02,  3.14095989e-02, -4.15256852e-03,
         4.36903425e-02,  1.71250161e-02, -8.00951570e-02,
         5.74005991e-02,  1.89092141e-02,  8.55261162e-02,
         3.96399684e-02, -1.34371862e-01, -1.44364685e-03,
         3.06711951e-03,  1.76854104e-01,  4.44885204e-03,
        -1.69274919e-02,  2.24267244e-02, -4.35050242e-02,
         6.09030714e-03, -9.98171326e-03, -6.23972081e-02,
         1.07372720e-02, -6.04900671e-03, -7.14660808e-02,
        -8.45804997e-03, -3.18020619e-02, -1.00518338e-01,
         2.25855489e-04, -1.89341214e-02, -3.17794606e-02,
         4.00861204e-02,  2.19178256e-02, -2.59528551e-02,
         5.84524274e-02, -8.12509730e-02,  2.12028679e-02,
        -5.02687581e-02,  1.32057117e-02,  1.32671441e-03,
         2.27062888e-02, -3.45793292e-02,  3.91547009e-02,
        -2.09433734e-02,  3.24822264e-03,  4.43960093e-02,
        -9.85357463e-02, -2.88894419e-02, -6.85027754e-03,
         5.38818575e-02,  6.46109730e-02, -2.45060213e-02,
         9.21827480e-02, -7.49869123e-02,  1.23995552e-02,
        -1.00026630e-01, -4.64910343e-02,  6.01570420e-02,
        -2.46480256e-02, -7.08076656e-02, -2.77270600e-02,
         9.72610861e-02,  3.85842025e-02, -1.44293038e-02,
        -7.46825244e-04, -1.04305055e-02, -1.61843169e-02,
         4.43627238e-02,  9.25993361e-03,  7.14165941e-02,
         6.37916997e-02,  4.94930446e-02, -6.02567680e-02,
         4.04806435e-02, -3.42860594e-02, -1.93881635e-02,
         6.61233962e-02,  6.01589493e-02,  1.09371310e-02,
        -5.38620912e-03,  1.44580584e-02,  9.25430357e-02,
        -3.14563625e-02, -1.84350982e-02,  9.91868414e-03,
        -1.85574889e-02,  1.31283607e-03,  2.26190423e-05,
         2.02730694e-03,  2.75255963e-02, -4.81927246e-02,
         5.42825423e-02, -7.32066780e-02,  4.88667563e-02,
         4.98490259e-02, -9.01142135e-03, -4.68905643e-02,
        -4.25886177e-02, -8.19524303e-02,  3.87105569e-02,
         7.85503760e-02,  1.46077096e-32,  1.66706406e-02,
         5.25494814e-02, -1.82449892e-02, -1.26686916e-02,
         6.52836785e-02, -2.11777482e-02, -4.06322852e-02,
         4.14947756e-02, -2.48361994e-02, -1.33068617e-02,
        -5.46753630e-02, -5.99126797e-04, -4.89248754e-03,
        -6.27359897e-02, -3.84877995e-02, -6.13543093e-02,
         8.27404857e-02,  2.34380644e-02, -8.63085315e-03,
         1.31003102e-02,  6.44213706e-02, -4.41360958e-02,
        -6.98632896e-02, -7.36060366e-02, -4.33264151e-02,
         6.96518784e-03, -5.05957082e-02, -1.60911679e-02,
        -5.66794425e-02,  3.35453521e-03,  5.34115806e-02,
         2.47761309e-02, -1.47985844e-02, -2.93242503e-02,
         7.30228946e-02, -1.86832882e-02,  8.13137889e-02,
        -2.69967727e-02, -5.68056107e-02, -6.59388602e-02,
        -5.95390424e-03,  2.85312869e-02, -7.85358325e-02,
        -2.76695518e-03, -3.26480437e-03, -9.28333551e-02,
        -7.27363825e-02, -3.31903920e-02,  1.01411134e-01,
         9.79880542e-02, -9.78740677e-02,  1.98668186e-02,
         2.38836948e-02, -1.81672890e-02, -3.73708159e-02,
         1.96553487e-03,  6.34425506e-02,  1.18271047e-02,
        -1.12041337e-02, -3.87315936e-02,  9.32424366e-02,
         4.26631607e-03, -1.66872609e-02, -6.87465221e-02,
         1.55119579e-02, -4.97755595e-02,  3.34493034e-02,
         8.00032839e-02,  2.12283209e-02,  1.34581864e-01,
        -2.30730046e-02,  5.53859174e-02,  3.07557750e-02,
        -2.93905586e-02,  2.31905449e-02, -9.34306532e-02,
         7.58034959e-02, -5.21201780e-03, -5.14522716e-02,
         3.32689211e-02,  3.67963687e-02, -1.06450683e-02,
         1.01635708e-02, -2.07650475e-02, -5.85519075e-02,
         4.79328595e-02,  2.13694368e-02,  8.76213014e-02,
         3.35488212e-03, -3.80336307e-02, -1.81204919e-02,
         6.87435782e-03,  5.15879653e-02, -4.75599244e-02,
        -6.12065345e-02, -1.45483604e-32,  4.12801886e-03,
         4.59648017e-03, -5.63901365e-02,  4.32475982e-03,
        -1.09450624e-03,  9.31960251e-03, -2.20267847e-02,
         5.79564050e-02, -1.44787868e-02,  4.64156680e-02,
         1.43542871e-01, -6.89756349e-02,  6.09631203e-02,
        -8.93744528e-02,  2.40919758e-02,  2.06010230e-02,
        -2.82415692e-02, -6.48315996e-02,  5.64794578e-02,
        -7.48342695e-03, -3.52058895e-02,  8.51060823e-02,
         1.30359689e-02,  2.02258099e-02, -1.44391358e-02,
        -4.63718288e-02,  1.77210215e-02,  1.59105640e-02,
        -9.51009840e-02, -3.54527608e-02,  2.08696071e-02,
         3.84376990e-03, -8.77918452e-02,  6.44575283e-02,
         1.44170858e-02,  3.84738925e-03,  4.70991097e-02,
         4.94662859e-02,  1.53863002e-02, -2.59578414e-02,
         9.10895690e-02,  1.83308162e-02, -5.89206517e-02,
         2.51992792e-02, -3.30374427e-02,  8.23344141e-02,
         1.74791962e-02,  6.48047999e-02, -1.19673861e-02,
        -3.31778601e-02,  3.00177820e-02,  3.54220569e-02,
        -1.39624784e-02,  6.69272840e-02,  3.87919843e-02,
         6.06916733e-02,  1.17960921e-03, -2.38786060e-02,
        -1.26930475e-01,  1.13847135e-02,  1.59290228e-02,
        -1.29426820e-02, -8.63248482e-02,  8.53665452e-03,
         6.03761636e-02,  1.51121700e-02, -1.19132452e-01,
         1.15234498e-02,  5.97089268e-02, -3.93345915e-02,
         1.55673930e-02,  1.04602408e-02, -4.72456142e-02,
        -2.59243678e-02,  9.98532306e-03,  3.07146497e-02,
        -7.14843199e-02,  6.98962156e-03, -1.55133391e-02,
         2.18864493e-02, -2.78146137e-02,  6.92733750e-02,
        -2.75904182e-02,  2.62429249e-02,  3.52562703e-02,
        -4.26419154e-02,  7.46278442e-04,  6.59866631e-02,
        -5.15105315e-02, -3.58434394e-02, -6.53440552e-03,
        -2.75858082e-02, -1.00125626e-01,  7.83325210e-02,
        -1.45798819e-02, -6.18457392e-08,  2.00325269e-02,
         6.59785271e-02, -2.04702448e-02,  1.64044909e-02,
         7.63000920e-02,  7.32182711e-02,  5.65789733e-03,
        -6.97747571e-04, -3.63795902e-03,  6.02394231e-02,
        -3.27187479e-02, -6.45838380e-02, -5.97952381e-02,
        -1.76696498e-02,  6.10150350e-03, -5.63484663e-03,
        -1.22972175e-01,  6.35818765e-02, -2.19432507e-02,
        -1.16406530e-01,  2.34364923e-02, -7.23524690e-02,
         2.31774077e-02, -6.55987337e-02, -7.42682219e-02,
         2.60146316e-02,  3.59756835e-02,  7.68432915e-02,
        -3.08056902e-02, -2.34793257e-02, -6.30425215e-02,
        -3.62158343e-02, -1.03560602e-02, -4.75602522e-02,
        -2.87521686e-02,  2.96401195e-02, -5.26904454e-03,
         5.67889847e-02, -3.74489278e-03,  3.09611764e-02,
         3.48227732e-02,  3.78607474e-02,  2.10155863e-02,
         2.70692110e-02,  5.25520705e-02,  7.16230050e-02,
        -5.53751038e-03,  4.01093848e-02,  5.16276695e-02,
        -2.67314650e-02,  5.94224297e-02, -4.29224409e-02,
        -1.19761173e-02,  3.05985492e-02, -7.40331411e-02,
         1.84221026e-02, -8.64863396e-03, -8.83558095e-02,
        -5.91984019e-02, -1.00842532e-04,  1.12913661e-01,
         4.57790261e-03, -4.25971895e-02,  3.22623784e-03],
       [ 8.04571435e-03, -3.57392244e-02,  4.93873283e-02,
        -7.19191274e-03,  6.17601327e-04, -9.05684605e-02,
         5.75595349e-02, -4.39445637e-02,  1.74751244e-02,
         5.21203168e-02, -4.62332293e-02,  2.49039512e-02,
         4.80810739e-02,  6.86636567e-02,  3.56147103e-02,
         3.00088599e-02,  2.61450484e-02, -9.05241743e-02,
        -8.02173838e-02,  5.04851192e-02, -7.90870860e-02,
        -1.76848914e-03, -2.48927623e-02,  9.02153403e-02,
         5.83691383e-03, -6.91070929e-02, -6.67965487e-02,
        -6.99113822e-03, -1.04566000e-01, -2.66474038e-02,
         3.05640306e-02,  2.02933811e-02,  2.25454085e-02,
        -4.22677817e-03,  1.11172507e-02,  6.78260848e-02,
         1.06073366e-02,  7.56635964e-02, -8.22778046e-02,
         8.45728163e-03, -6.97611570e-02, -4.21974808e-02,
        -1.05675152e-02,  2.23673470e-02,  5.64496666e-02,
         8.16498883e-03,  1.09344028e-01,  3.16565335e-02,
        -1.76923815e-02, -3.21071856e-02, -3.39975767e-02,
        -4.91786923e-04,  3.72878276e-03,  2.83771660e-02,
        -1.28521193e-02, -1.07935071e-03, -6.32418394e-02,
         6.89900890e-02,  1.77270155e-02, -5.20958900e-02,
         8.28311220e-03,  5.45032471e-02, -5.42099513e-02,
        -4.53332514e-02, -4.07493673e-02, -2.82698348e-02,
         1.23605952e-02, -2.13816501e-02, -2.36266311e-02,
         1.25317900e-02, -2.37170346e-02,  3.97411659e-02,
        -1.24362200e-01,  7.60625973e-02,  5.50833605e-02,
         8.28217193e-02,  2.97119375e-02, -1.84067711e-02,
        -1.96195040e-02,  5.54319210e-02, -3.49144340e-02,
        -4.14677560e-02, -3.37047391e-02,  7.31324926e-02,
         4.41837087e-02,  2.55246330e-02, -8.26406199e-03,
        -1.07323211e-02, -4.26243730e-02, -2.84964149e-03,
         7.38558918e-02,  2.27768552e-02,  7.15425762e-04,
         4.36012670e-02,  5.09079918e-02,  6.38482422e-02,
        -2.73155421e-02, -6.55021667e-02, -7.69265145e-02,
         3.55171636e-02,  9.60494503e-02,  2.18195673e-02,
         1.20155085e-02, -1.17863519e-02, -4.57931729e-03,
        -8.58036242e-03,  3.37150581e-02,  2.31918581e-02,
        -7.58325830e-02, -5.23878597e-02,  4.53933515e-02,
        -3.80785875e-02, -3.34904753e-02,  9.20352861e-02,
         2.87689175e-02, -3.33817676e-02, -1.95851224e-03,
        -3.04574991e-04, -1.70499664e-02,  2.85335500e-02,
        -8.81096125e-02, -4.02252525e-02, -4.00092639e-02,
        -1.03192739e-02, -2.51968186e-02,  2.14093160e-02,
         1.31045297e-01, -5.29635556e-34, -1.09651744e-01,
         1.29811605e-02,  5.92654757e-03,  4.73506488e-02,
        -8.60290788e-03, -3.67089249e-02,  3.05214748e-02,
         5.53066619e-02, -4.71984968e-02, -1.25118969e-02,
        -1.15366459e-01,  9.08003561e-03,  1.07346557e-01,
        -4.94735166e-02, -1.34290578e-02, -4.61562946e-02,
         2.45320108e-02,  9.45081376e-03,  2.04324275e-02,
        -3.99918258e-02, -4.67826203e-02,  2.21171305e-02,
        -4.58187126e-02, -8.13270174e-03, -7.65664317e-03,
         1.92284007e-02,  4.85844314e-02, -2.55902447e-02,
         1.61541766e-03, -1.37180518e-02,  9.67307854e-03,
         7.36415340e-03,  1.14088180e-02,  1.28853455e-01,
         7.71834049e-03,  7.06362128e-02,  2.54451782e-02,
         4.06523719e-02,  2.44039148e-02,  1.43776638e-02,
        -6.00932389e-02,  7.38180950e-02, -2.44701412e-02,
         8.98901969e-02,  3.17048165e-03,  1.01834446e-01,
         4.17741574e-02, -5.95178045e-02, -3.23182493e-02,
         3.80938537e-02,  1.21155586e-02, -4.07834202e-02,
         2.84823496e-02,  4.90988195e-02, -9.35704820e-03,
         6.50073960e-02,  7.23532587e-02, -1.67793557e-02,
        -8.22416879e-03, -1.61572993e-02,  5.96225597e-02,
        -3.36083882e-02,  2.12108120e-02, -6.06091283e-02,
         1.54377654e-01, -7.24145994e-02, -3.77272144e-02,
        -3.26890238e-02, -1.80383853e-03, -1.01959873e-02,
        -1.60680851e-03, -6.91846311e-02,  8.28444958e-02,
         9.88839939e-02,  3.45471827e-03, -9.90247279e-02,
        -3.52827199e-02, -7.13178888e-02, -4.96000424e-02,
        -3.43954898e-02, -8.13041851e-02,  4.81447354e-02,
         5.00680553e-03, -2.21499279e-02, -5.60057089e-02,
         1.00068180e-02, -3.59794125e-02,  1.06184304e-01,
        -4.54196781e-02,  7.16393366e-02, -2.36773286e-02,
         9.98144876e-03,  2.73602754e-02,  1.05985418e-01,
         4.60164621e-02,  9.59028811e-34, -1.12306982e-01,
         2.78912503e-02, -3.35900933e-02,  5.39242513e-02,
        -2.22290792e-02,  1.53769003e-02,  3.10411118e-02,
         3.39010470e-02,  7.43166879e-02,  3.42470892e-02,
        -3.35058663e-03, -2.05351152e-02, -3.62369828e-02,
         2.29334272e-02, -3.01991813e-02, -1.00819916e-01,
         3.29194479e-02,  6.77542537e-02,  1.35644851e-02,
        -5.20551018e-03, -6.58158809e-02,  9.54550803e-02,
        -1.34039167e-02,  1.53884888e-02, -7.22936317e-02,
         9.67836380e-02, -8.08119774e-02, -4.53450298e-03,
        -6.42011613e-02, -4.99278493e-02,  4.64197434e-02,
         2.21340638e-02,  3.13109830e-02,  9.13568884e-02,
        -4.61120084e-02, -1.02761097e-01,  3.04415412e-02,
         5.09875938e-02,  6.70140833e-02,  1.04042664e-02,
         1.63534116e-02,  3.92031036e-02,  2.17154529e-02,
         5.36604039e-02,  3.62809859e-02, -4.22140285e-02,
        -2.47227512e-02,  1.90311894e-02,  3.61723788e-02,
         6.37021437e-02, -3.21587035e-03, -8.50392785e-03,
         3.94655652e-02,  9.02653858e-03,  1.93095598e-02,
         6.60718530e-02,  1.02695031e-02, -4.43853736e-02,
        -1.56523231e-02, -1.55713819e-02,  1.32904593e-02,
        -1.16108665e-02,  4.21831720e-02, -5.44776656e-02,
         1.29237205e-01, -2.25757826e-02,  5.26204295e-02,
        -1.58437248e-02,  9.33165401e-02,  6.38017012e-03,
        -9.36162379e-03, -6.08875453e-02, -3.27308178e-02,
        -3.44816931e-02,  3.29974256e-02, -4.79391851e-02,
        -9.81301218e-02,  2.91165207e-02, -2.70903204e-02,
         1.81867145e-02, -1.73860621e-02, -4.40371595e-02,
        -7.97002017e-02,  3.01647168e-02, -6.35260642e-02,
         1.25963185e-02,  8.50250348e-02, -4.58910689e-02,
         5.81017435e-02, -2.71002967e-02,  8.42775777e-02,
        -4.09972668e-02, -3.37656662e-02,  1.02088610e-02,
        -2.54193339e-02, -1.40610261e-08,  4.94446829e-02,
        -9.04356316e-02, -6.06710128e-02,  8.29529613e-02,
        -3.29032317e-02,  4.14911099e-02,  9.99588706e-03,
         6.96135871e-03,  3.99235310e-03, -3.24332975e-02,
        -3.14656794e-02, -5.33161424e-02, -3.80912982e-02,
         1.62076950e-02,  2.45778617e-02, -7.26419464e-02,
        -6.56893998e-02, -8.23131725e-02, -8.00501183e-02,
        -5.36649153e-02,  5.60894683e-02, -1.10913347e-02,
         9.62170248e-04, -1.22690305e-01, -5.13837002e-02,
         9.96699184e-03,  1.00696124e-02,  1.07073054e-01,
         1.19758239e-02,  1.00423349e-02, -6.28261715e-02,
        -7.49696791e-02, -6.34072581e-03, -2.72201188e-02,
        -1.28096133e-01, -2.62460317e-02, -1.81464553e-02,
        -9.85359848e-02, -3.02990489e-02, -4.02614772e-02,
         9.94291157e-02,  5.35999462e-02,  2.74899434e-02,
        -5.53677836e-03,  8.43571275e-02,  8.35161880e-02,
         3.74304689e-02,  7.11937919e-02,  2.98903249e-02,
         2.32728496e-02, -3.62112783e-02,  6.20540194e-02,
         2.15147790e-02,  5.19732460e-02,  1.45338112e-02,
        -4.60966639e-02,  5.02554253e-02, -7.27027655e-02,
         2.92778704e-02,  5.62662967e-02, -3.86355072e-02,
         1.53831402e-02, -6.23094998e-02, -2.77466811e-02]], dtype=float32)

In [10]:
print(embeddings.shape)

(2410, 384)

In [15]:
# Cluster embeddings using DBSCAN
dbscan = DBSCAN(eps=0.1, min_samples=1, metric='cosine')
clusters = dbscan.fit_predict(embeddings)

# Add cluster labels to the dataframe
df['cluster'] = clusters
df.head()

,timestamp,source,log_message,target_label,complexity,cluster
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,bert,0
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,bert,1
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,bert,2
3,2025-07-12 00:24:16,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,bert,0
4,2025-06-02 18:25:23,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,bert,0

In [16]:
df[df.cluster == 1]

,timestamp,source,log_message,target_label,complexity,cluster
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,bert,1
361,11/19/2025 23:06,BillingSystem,Email service experienced a sending issue,Error,bert,1
1901,9/22/2025 2:52,ThirdPartyAPI,Email service experienced a mail sending issue,Error,bert,1

In [18]:
# Count records per cluster and sort descending
cluster_counts = df['cluster'].value_counts().sort_values(ascending=False)

# Iterate clusters with more than 10 records and print 5 log messages from each
for cluster_id, count in cluster_counts.items():
    if count > 10:
        print(f"\nCluster {cluster_id} (records: {count}):")
        sample_logs = df[df['cluster'] == cluster_id]['log_message'].head(5)
        for log in sample_logs:
            print(log)

Cluster 0 (records: 765):
nova.osapi_compute.wsgi.server [req-b9718cd8-f65e-49cc-8349-6cf7122af137 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" status: 200 len: 1893 time: 0.2675118
nova.osapi_compute.wsgi.server [req-4895c258-b2f8-488f-a2a3-4fae63982e48 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" HTTP status code -  200 len: 211 time: 0.0968180
nova.osapi_compute.wsgi.server [req-ee8bc8ba-9265-4280-9215-dbe000a41209 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" RCODE  200 len: 1874 time: 0.2280791
nova.osapi_compute.wsgi.server [req-f0bffbc3-5ab0-4916-91c1-0a61dd7d4ec2 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" Return code: 200 len: 1874 time: 0.2131531
nova.osapi_compute.wsgi.server [req-2bf7cfee-a236-42f3-8fb1-96fefab0b302 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] 10.11.10.1 "GET /v2/54fadb412c4e40cdbaed9335e4c35a9e/servers/detail HTTP/1.1" RCODE  200 len: 1874 time: 0.1794369

Cluster 16 (records: 179):
nova.metadata.wsgi.server [-] 10.11.21.138,10.11.10.1 "GET /openstack/2013-10-17 HTTP/1.1" RCODE  200 len: 157 time: 0.0010941
nova.metadata.wsgi.server [req-61196723-e034-487d-82e0-9cc159c8572c - - - - -] 10.11.21.123,10.11.10.1 "GET /openstack/2013-10-17/vendor_data.json HTTP/1.1" status: 200 len: 124 time: 0.2335150
nova.metadata.wsgi.server [req-7d3eeb2d-3948-433a-8002-d969d2f86863 - - - - -] 10.11.21.132,10.11.10.1 "GET /openstack/2012-08-10/meta_data.json HTTP/1.1" Return code: 200 len: 264 time: 0.2316251
nova.metadata.wsgi.server [-] 10.11.21.137,10.11.10.1 "GET /openstack/2013-10-17/meta_data.json HTTP/1.1" HTTP status code -  200 len: 967 time: 0.0013261
nova.metadata.wsgi.server [req-e0d4ce94-e0cb-41b5-9192-c6b9fdd49a94 - - - - -] 10.11.21.139,10.11.10.1 "GET /openstack/2012-08-10/meta_data.json HTTP/1.1" status: 200 len: 264 time: 0.2261620

Cluster 15 (records: 86):
Backup started at 2025-05-14 07:06:55.
Backup started at 2025-02-15 20:00:19.
Backup ended at 2025-08-08 13:06:23.
Backup started at 2025-11-14 08:27:43.
Backup started at 2025-12-09 10:19:11.

Cluster 5 (records: 84):
nova.compute.claims [req-a07ac654-8e81-416d-bfbb-189116b07969 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: bf8c824d-f099-4433-a41e-e3da7578262e] Total memory: 64172 MB, used: 512.00 MB
nova.compute.claims [req-d6986b54-3735-4a42-9074-0ba7d9717de9 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: af5f7392-f7d4-4298-b647-c98924c64aa1] memory limit: 96258.00 MB, free: 95746.00 MB
nova.compute.claims [req-d82fab16-60f8-4c9f-bde8-f362f57bdd40 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: ae3a1b5d-eec1-45bb-b76a-c59d83b1471f] memory limit: 96258.00 MB, free: 95746.00 MB
nova.compute.claims [req-2d658d2c-7eff-414e-a68f-3f1c75c9e874 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: 7e7cc42f-3cb9-4d91-804c-f5a32d54f1c5] Total disk: 15 GB, used: 0.00 GB
nova.compute.claims [req-9118475d-6e72-48fa-9dee-e6b7d957dcd6 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: be793e89-2cc3-4f99-9884-9c6a624a84bc] Attempting claim: memory 2048 MB, disk 20 GB, vcpus 1 CPU

Cluster 9 (records: 60):
Backup completed successfully.
Backup completed successfully.
Backup completed successfully.
Backup completed successfully.
Backup completed successfully.

Cluster 27 (records: 58):
System updated to version 3.9.1.
System updated to version 5.5.4.
System updated to version 4.7.4.
System updated to version 3.7.7.
System updated to version 2.6.2.

Cluster 13 (records: 56):
User User685 logged out.
User User494 logged out.
User User272 logged out.
User User706 logged out.
User User881 logged out.

Cluster 4 (records: 53):
File data_6169.csv uploaded successfully by user User953.
File data_3847.csv uploaded successfully by user User175.
File data_7366.csv uploaded successfully by user User282.
File data_1206.csv uploaded successfully by user User359.
File data_1503.csv uploaded successfully by user User151.

Cluster 45 (records: 51):
Disk cleanup completed successfully.
Disk cleanup completed successfully.
Disk cleanup completed successfully.
Disk cleanup completed successfully.
Disk cleanup completed successfully.

Cluster 20 (records: 48):
System reboot initiated by user User243.
System reboot initiated by user User471.
System reboot initiated by user User216.
System reboot initiated by user User639.
System reboot initiated by user User819.

Cluster 11 (records: 43):
nova.osapi_compute.wsgi.server [req-033d97b9-69e4-4acd-9029-f0d7b9370645 f7b8d1f1d4d44643b07fa10ca7d021fb e9746973ac574c6b8a9e8857f56a7608 - - -] 10.11.10.1 "POST /v2/e9746973ac574c6b8a9e8857f56a7608/os-server-external-events HTTP/1.1" status: 404 len: 296 time: 0.0847020
nova.osapi_compute.wsgi.server [req-d6e9cfb8-d914-48c3-b677-72bc73329c69 f7b8d1f1d4d44643b07fa10ca7d021fb e9746973ac574c6b8a9e8857f56a7608 - - -] 10.11.10.1 "POST /v2/e9746973ac574c6b8a9e8857f56a7608/os-server-external-events HTTP/1.1" Status code -  404 len: 296 time: 0.0934131
nova.osapi_compute.wsgi.server [req-8c36e637-8e89-4cbe-813d-c5f46cc79818 f7b8d1f1d4d44643b07fa10ca7d021fb e9746973ac574c6b8a9e8857f56a7608 - - -] 10.11.10.1 "POST /v2/e9746973ac574c6b8a9e8857f56a7608/os-server-external-events HTTP/1.1" status: 200 len: 380 time: 0.0919530
nova.osapi_compute.wsgi.server [req-0b7fefce-6f00-464a-969a-d6799e8bba35 f7b8d1f1d4d44643b07fa10ca7d021fb e9746973ac574c6b8a9e8857f56a7608 - - -] 10.11.10.1 "POST /v2/e9746973ac574c6b8a9e8857f56a7608/os-server-external-events HTTP/1.1" Return code: 200 len: 380 time: 0.0926709
nova.osapi_compute.wsgi.server [req-60f50a9d-827b-4fc8-b8c7-dc0bbe15c936 f7b8d1f1d4d44643b07fa10ca7d021fb e9746973ac574c6b8a9e8857f56a7608 - - -] 10.11.10.1 "POST /v2/e9746973ac574c6b8a9e8857f56a7608/os-server-external-events HTTP/1.1" RCODE  404 len: 296 time: 0.0870681

Cluster 31 (records: 43):
User User395 logged in.
User User225 logged in.
User User900 logged in.
User User799 logged in.
User User496 logged in.

Cluster 3 (records: 42):
Shard 6 replication task ended in failure
Data replication task for shard 14 did not complete
Data replication task failed for shard 17
Replication of data to shard 14 failed
Data replication task for shard 6 did not complete

Cluster 21 (records: 27):
nova.metadata.wsgi.server [req-27e91939-3ba4-4d14-80e1-47d8fbb230ff - - - - -] 10.11.21.126,10.11.10.1 "GET /latest/meta-data/block-device-mapping/root HTTP/1.1" Status code -  200 len: 124 time: 0.2206309
nova.metadata.wsgi.server [-] 10.11.21.143,10.11.10.1 "GET /latest/meta-data/block-device-mapping/root HTTP/1.1" HTTP status code -  200 len: 124 time: 0.0009151
nova.metadata.wsgi.server [req-705dd9dc-0fad-4523-b0ef-0524abc6f12a - - - - -] 10.11.21.135,10.11.10.1 "GET /latest/meta-data/block-device-mapping/ HTTP/1.1" status: 200 len: 124 time: 0.2319629
nova.metadata.wsgi.server [-] 10.11.21.129,10.11.10.1 "GET /latest/meta-data/block-device-mapping/ HTTP/1.1" HTTP status code -  200 len: 124 time: 0.0010171
nova.metadata.wsgi.server [req-7fd3da99-a9b0-4dec-8a14-37be960fd707 - - - - -] 10.11.21.139,10.11.10.1 "GET /latest/meta-data/block-device-mapping/ HTTP/1.1" HTTP status code -  200 len: 124 time: 0.2223170

Cluster 23 (records: 21):
nova.compute.claims [req-72b4858f-049e-49e1-b31e-b562c5018eaf 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: 63a0d960-70b6-44c6-b606-491478a5cadf] disk limit not specified, defaulting to unlimited
nova.compute.claims [req-d38f479d-9bb9-4276-9688-52607e8fd350 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: 95960536-049b-41f6-9049-05fc479b6a7c] disk limit not specified, defaulting to unlimited
nova.compute.claims [req-6a763803-4838-49c7-814e-eaefbaddee9d 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: 96abccce-8d1f-4e07-b6d1-4b2ab87e23b4] disk limit not specified, defaulting to unlimited
nova.compute.claims [req-a07ac654-8e81-416d-bfbb-189116b07969 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: bf8c824d-f099-4433-a41e-e3da7578262e] disk limit not specified, defaulting to unlimited
nova.compute.claims [req-01d570b0-78a7-4719-b7a3-429fd7dc5a3f 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: d54b44eb-2d1a-4aa2-ba6b-074d35f8f12c] disk limit not specified, defaulting to unlimited

Cluster 32 (records: 21):
nova.compute.claims [req-5c8f52bd-8e3c-41f0-95a5-7861d247cafa 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: d96a117b-0193-4549-bdcc-63b917273d1d] vcpu limit not specified, defaulting to unlimited
nova.compute.claims [req-01d570b0-78a7-4719-b7a3-429fd7dc5a3f 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: d54b44eb-2d1a-4aa2-ba6b-074d35f8f12c] vcpu limit not specified, defaulting to unlimited
nova.compute.claims [req-4b4dd551-26d8-48e2-bd52-91793d2157bc 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: a015cf14-84bb-4156-a48d-7c4824ac7a9d] vcpu limit not specified, defaulting to unlimited
nova.compute.claims [req-d82fab16-60f8-4c9f-bde8-f362f57bdd40 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: ae3a1b5d-eec1-45bb-b76a-c59d83b1471f] vcpu limit not specified, defaulting to unlimited
nova.compute.claims [req-72b4858f-049e-49e1-b31e-b562c5018eaf 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: 63a0d960-70b6-44c6-b606-491478a5cadf] vcpu limit not specified, defaulting to unlimited

Cluster 52 (records: 21):
nova.compute.claims [req-868a5460-dbb6-416b-b4c4-a98abae6c847 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: 17288ea8-cbf4-4f0e-94fe-853fd2735f29] Total vcpu: 16 VCPU, used: 0.00 VCPU
nova.compute.claims [req-29a09cdb-3169-4c40-8bd1-552636286362 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: 43204226-2f87-4da7-b7ee-4d20cc66e846] Total vcpu: 16 VCPU, used: 0.00 VCPU
nova.compute.claims [req-d82fab16-60f8-4c9f-bde8-f362f57bdd40 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: ae3a1b5d-eec1-45bb-b76a-c59d83b1471f] Total vcpu: 16 VCPU, used: 0.00 VCPU
nova.compute.claims [req-3d26bc3d-373c-4269-b095-004aab7a9785 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: faf974ea-cba5-4e1b-93f4-3a3bc606006f] Total vcpu: 16 VCPU, used: 0.00 VCPU
nova.compute.claims [req-4b4dd551-26d8-48e2-bd52-91793d2157bc 113d3a99c3da401fbd62cc2caa5b96d2 54fadb412c4e40cdbaed9335e4c35a9e - - -] [instance: a015cf14-84bb-4156-a48d-7c4824ac7a9d] Total vcpu: 16 VCPU, used: 0.00 VCPU

Cluster 92 (records: 20):
Service health check was not successful because of SSL certificate validation failures.
Invalid SSL certificate resulted in a failed service health check.
Service health check failure was due to an invalid or improperly configured SSL certificate.
An issue with the SSL certificate caused the service health check to fail.
Service health check failure was caused by an expired SSL certificate.

Cluster 12 (records: 15):
nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Final resource view: name=cp-1.slowvm1.tcloud-pg0.utah.cloudlab.us phys_ram=64172MB used_ram=512MB phys_disk=15GB used_disk=0GB total_vcpus=16 used_vcpus=0 pci_stats=[]
nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Final resource view: name=cp-1.slowvm1.tcloud-pg0.utah.cloudlab.us phys_ram=64172MB used_ram=2560MB phys_disk=15GB used_disk=20GB total_vcpus=16 used_vcpus=1 pci_stats=[]
nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Final resource view: name=cp-1.slowvm1.tcloud-pg0.utah.cloudlab.us phys_ram=64172MB used_ram=2560MB phys_disk=15GB used_disk=20GB total_vcpus=16 used_vcpus=1 pci_stats=[]
nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Final resource view: name=cp-1.slowvm1.tcloud-pg0.utah.cloudlab.us phys_ram=64172MB used_ram=2560MB phys_disk=15GB used_disk=20GB total_vcpus=16 used_vcpus=1 pci_stats=[]
nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Final resource view: name=cp-1.slowvm1.tcloud-pg0.utah.cloudlab.us phys_ram=64172MB used_ram=2560MB phys_disk=15GB used_disk=20GB total_vcpus=16 used_vcpus=1 pci_stats=[]

Cluster 57 (records: 15):
nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Total usable vcpus: 16, total allocated vcpus: 0
nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Total usable vcpus: 16, total allocated vcpus: 1
nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Total usable vcpus: 16, total allocated vcpus: 0
nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Total usable vcpus: 16, total allocated vcpus: 0
nova.compute.resource_tracker [req-addc1839-2ed5-4778-b57e-5854eb7b8b09 - - - - -] Total usable vcpus: 16, total allocated vcpus: 1

Cluster 59 (records: 13):
Account with ID 7813 created by User373.
Account with ID 9827 created by User965.
Account with ID 3889 created by User852.
Account with ID 8884 created by User893.
Account with ID 4725 created by User771.

In [19]:
import re
def classify_with_regex(log_message):
    regex_patterns = {
        r"User User\d+ logged (in|out).": "User Action",
        r"Backup (started|ended) at .*": "System Notification",
        r"Backup completed successfully.": "System Notification",
        r"System updated to version .*": "System Notification",
        r"File .* uploaded successfully by user .*": "System Notification",
        r"Disk cleanup completed successfully.": "System Notification",
        r"System reboot initiated by user .*": "System Notification",
        r"Account with ID .* created by .*": "User Action"
    }
    for pattern, label in regex_patterns.items():
        if re.search(pattern, log_message):
            return label
    return None

In [20]:
classify_with_regex("User User123 logged in.")

'User Action'

In [21]:
classify_with_regex("System reboot initiated by user User179.")

'System Notification'

In [22]:
classify_with_regex("Hey there, this is a random log message that doesn't match any pattern.")

In [23]:
# Apply regex classification
df['regex_label'] = df['log_message'].apply(lambda x: classify_with_regex(x))
df[df['regex_label'].notnull()]

,timestamp,source,log_message,target_label,complexity,cluster,regex_label
7,10/11/2025 8:44,ModernHR,File data_6169.csv uploaded successfully by us...,System Notification,regex,4,System Notification
14,1/4/2025 1:43,ThirdPartyAPI,File data_3847.csv uploaded successfully by us...,System Notification,regex,4,System Notification
15,5/1/2025 9:41,ModernCRM,Backup completed successfully.,System Notification,regex,9,System Notification
18,2/22/2025 17:49,ModernCRM,Account with ID 5351 created by User634.,User Action,regex,10,User Action
27,9/24/2025 19:57,ThirdPartyAPI,User User685 logged out.,User Action,regex,13,User Action
...,...,...,...,...,...,...,...
2376,6/27/2025 8:47,ModernCRM,System updated to version 2.0.5.,System Notification,regex,27,System Notification
2381,9/5/2025 6:39,ThirdPartyAPI,Disk cleanup completed successfully.,System Notification,regex,45,System Notification
2394,4/3/2025 13:13,ModernHR,Disk cleanup completed successfully.,System Notification,regex,45,System Notification
2395,5/2/2025 14:29,ThirdPartyAPI,Backup ended at 2025-05-06 11:23:16.,System Notification,regex,15,System Notification
2403,10/1/2025 1:31,ModernCRM,Backup completed successfully.,System Notification,regex,9,System Notification

In [24]:
df[df['regex_label'].isnull()].head(5)

,timestamp,source,log_message,target_label,complexity,cluster,regex_label
0,2025-06-27 07:20:25,ModernCRM,nova.osapi_compute.wsgi.server [req-b9718cd8-f...,HTTP Status,bert,0,NaN
1,1/14/2025 23:07,ModernCRM,Email service experiencing issues with sending,Critical Error,bert,1,NaN
2,1/17/2025 1:29,AnalyticsEngine,Unauthorized access to data was attempted,Security Alert,bert,2,NaN
3,2025-07-12 00:24:16,ModernHR,nova.osapi_compute.wsgi.server [req-4895c258-b...,HTTP Status,bert,0,NaN
4,2025-06-02 18:25:23,BillingSystem,nova.osapi_compute.wsgi.server [req-ee8bc8ba-9...,HTTP Status,bert,0,NaN

Classification Stage 2: Classification Using Embeddings

In [25]:
df_non_regex = df[df['regex_label'].isnull()].copy()
df_non_regex.shape

(1910, 7)

In [27]:
label_counts = df_non_regex['target_label'].value_counts()
rare_labels = label_counts[label_counts <= 5].index
print(df_non_regex[df_non_regex['target_label'].isin(rare_labels)]['target_label'].unique())

<StringArray>
['Workflow Error', 'Deprecation Warning']
Length: 2, dtype: str

Classification using LLM for log sources having less than 5 rows or log entries

In [26]:
df_legacy = df_non_regex[df_non_regex.source=="LegacyCRM"]
df_legacy

,timestamp,source,log_message,target_label,complexity,cluster,regex_label
60,2025-10-06 16:55:23,LegacyCRM,Lead conversion failed for prospect ID 7842 du...,Workflow Error,llm,33,NaN
255,2025-05-03 16:55:35,LegacyCRM,API endpoint 'getCustomerDetails' is deprecate...,Deprecation Warning,llm,83,NaN
377,2025-06-24 12:16:29,LegacyCRM,Customer follow-up process for lead ID 5621 fa...,Workflow Error,llm,117,NaN
1325,2025-04-17 07:33:44,LegacyCRM,Escalation rule execution failed for ticket ID...,Workflow Error,llm,311,NaN
1734,2025-04-30 07:47:30,LegacyCRM,The 'ExportToCSV' feature is outdated. Please ...,Deprecation Warning,llm,382,NaN
1826,2025-01-23 10:33:36,LegacyCRM,Support for legacy authentication methods will...,Deprecation Warning,llm,402,NaN
2217,2025-05-12 09:46:54,LegacyCRM,Task assignment for TeamID 3425 could not comp...,Workflow Error,llm,478,NaN

Classification using BERT for log sources having 5 or more than 5 rows or log entries

In [30]:
df_non_legacy = df_non_regex[df_non_regex.source != "LegacyCRM"]
df_non_legacy.source.unique()

<StringArray>
['ModernCRM', 'AnalyticsEngine', 'ModernHR', 'BillingSystem', 'ThirdPartyAPI']
Length: 5, dtype: str

In [31]:
filtered_embeddings = model.encode(df_non_legacy['log_message'].tolist())

filtered_embeddings[:2]

array([[-1.02939643e-01,  3.35459560e-02, -2.20260546e-02,
         1.55099435e-03, -9.86917224e-03, -1.78956345e-01,
        -6.34410158e-02, -6.01762161e-02,  2.81108748e-02,
         5.99619932e-02, -1.72618870e-02,  1.43367937e-03,
        -1.49560049e-01,  3.15283053e-03, -5.66030554e-02,
         2.71685459e-02, -1.49890343e-02, -3.54037508e-02,
        -3.62936072e-02, -1.45410430e-02, -5.61489770e-03,
         8.75538886e-02,  4.55121212e-02,  2.50963587e-02,
         1.00187939e-02,  1.24266772e-02, -1.39923558e-01,
         7.68696293e-02,  3.14095989e-02, -4.15256852e-03,
         4.36903425e-02,  1.71250161e-02, -8.00951570e-02,
         5.74005991e-02,  1.89092141e-02,  8.55261162e-02,
         3.96399684e-02, -1.34371862e-01, -1.44364685e-03,
         3.06711951e-03,  1.76854104e-01,  4.44885204e-03,
        -1.69274919e-02,  2.24267244e-02, -4.35050242e-02,
         6.09030714e-03, -9.98171326e-03, -6.23972081e-02,
         1.07372720e-02, -6.04900671e-03, -7.14660808e-02,
        -8.45804997e-03, -3.18020619e-02, -1.00518338e-01,
         2.25855489e-04, -1.89341214e-02, -3.17794606e-02,
         4.00861204e-02,  2.19178256e-02, -2.59528551e-02,
         5.84524274e-02, -8.12509730e-02,  2.12028679e-02,
        -5.02687581e-02,  1.32057117e-02,  1.32671441e-03,
         2.27062888e-02, -3.45793292e-02,  3.91547009e-02,
        -2.09433734e-02,  3.24822264e-03,  4.43960093e-02,
        -9.85357463e-02, -2.88894419e-02, -6.85027754e-03,
         5.38818575e-02,  6.46109730e-02, -2.45060213e-02,
         9.21827480e-02, -7.49869123e-02,  1.23995552e-02,
        -1.00026630e-01, -4.64910343e-02,  6.01570420e-02,
        -2.46480256e-02, -7.08076656e-02, -2.77270600e-02,
         9.72610861e-02,  3.85842025e-02, -1.44293038e-02,
        -7.46825244e-04, -1.04305055e-02, -1.61843169e-02,
         4.43627238e-02,  9.25993361e-03,  7.14165941e-02,
         6.37916997e-02,  4.94930446e-02, -6.02567680e-02,
         4.04806435e-02, -3.42860594e-02, -1.93881635e-02,
         6.61233962e-02,  6.01589493e-02,  1.09371310e-02,
        -5.38620912e-03,  1.44580584e-02,  9.25430357e-02,
        -3.14563625e-02, -1.84350982e-02,  9.91868414e-03,
        -1.85574889e-02,  1.31283607e-03,  2.26190423e-05,
         2.02730694e-03,  2.75255963e-02, -4.81927246e-02,
         5.42825423e-02, -7.32066780e-02,  4.88667563e-02,
         4.98490259e-02, -9.01142135e-03, -4.68905643e-02,
        -4.25886177e-02, -8.19524303e-02,  3.87105569e-02,
         7.85503760e-02,  1.46077096e-32,  1.66706406e-02,
         5.25494814e-02, -1.82449892e-02, -1.26686916e-02,
         6.52836785e-02, -2.11777482e-02, -4.06322852e-02,
         4.14947756e-02, -2.48361994e-02, -1.33068617e-02,
        -5.46753630e-02, -5.99126797e-04, -4.89248754e-03,
        -6.27359897e-02, -3.84877995e-02, -6.13543093e-02,
         8.27404857e-02,  2.34380644e-02, -8.63085315e-03,
         1.31003102e-02,  6.44213706e-02, -4.41360958e-02,
        -6.98632896e-02, -7.36060366e-02, -4.33264151e-02,
         6.96518784e-03, -5.05957082e-02, -1.60911679e-02,
        -5.66794425e-02,  3.35453521e-03,  5.34115806e-02,
         2.47761309e-02, -1.47985844e-02, -2.93242503e-02,
         7.30228946e-02, -1.86832882e-02,  8.13137889e-02,
        -2.69967727e-02, -5.68056107e-02, -6.59388602e-02,
        -5.95390424e-03,  2.85312869e-02, -7.85358325e-02,
        -2.76695518e-03, -3.26480437e-03, -9.28333551e-02,
        -7.27363825e-02, -3.31903920e-02,  1.01411134e-01,
         9.79880542e-02, -9.78740677e-02,  1.98668186e-02,
         2.38836948e-02, -1.81672890e-02, -3.73708159e-02,
         1.96553487e-03,  6.34425506e-02,  1.18271047e-02,
        -1.12041337e-02, -3.87315936e-02,  9.32424366e-02,
         4.26631607e-03, -1.66872609e-02, -6.87465221e-02,
         1.55119579e-02, -4.97755595e-02,  3.34493034e-02,
         8.00032839e-02,  2.12283209e-02,  1.34581864e-01,
        -2.30730046e-02,  5.53859174e-02,  3.07557750e-02,
        -2.93905586e-02,  2.31905449e-02, -9.34306532e-02,
         7.58034959e-02, -5.21201780e-03, -5.14522716e-02,
         3.32689211e-02,  3.67963687e-02, -1.06450683e-02,
         1.01635708e-02, -2.07650475e-02, -5.85519075e-02,
         4.79328595e-02,  2.13694368e-02,  8.76213014e-02,
         3.35488212e-03, -3.80336307e-02, -1.81204919e-02,
         6.87435782e-03,  5.15879653e-02, -4.75599244e-02,
        -6.12065345e-02, -1.45483604e-32,  4.12801886e-03,
         4.59648017e-03, -5.63901365e-02,  4.32475982e-03,
        -1.09450624e-03,  9.31960251e-03, -2.20267847e-02,
         5.79564050e-02, -1.44787868e-02,  4.64156680e-02,
         1.43542871e-01, -6.89756349e-02,  6.09631203e-02,
        -8.93744528e-02,  2.40919758e-02,  2.06010230e-02,
        -2.82415692e-02, -6.48315996e-02,  5.64794578e-02,
        -7.48342695e-03, -3.52058895e-02,  8.51060823e-02,
         1.30359689e-02,  2.02258099e-02, -1.44391358e-02,
        -4.63718288e-02,  1.77210215e-02,  1.59105640e-02,
        -9.51009840e-02, -3.54527608e-02,  2.08696071e-02,
         3.84376990e-03, -8.77918452e-02,  6.44575283e-02,
         1.44170858e-02,  3.84738925e-03,  4.70991097e-02,
         4.94662859e-02,  1.53863002e-02, -2.59578414e-02,
         9.10895690e-02,  1.83308162e-02, -5.89206517e-02,
         2.51992792e-02, -3.30374427e-02,  8.23344141e-02,
         1.74791962e-02,  6.48047999e-02, -1.19673861e-02,
        -3.31778601e-02,  3.00177820e-02,  3.54220569e-02,
        -1.39624784e-02,  6.69272840e-02,  3.87919843e-02,
         6.06916733e-02,  1.17960921e-03, -2.38786060e-02,
        -1.26930475e-01,  1.13847135e-02,  1.59290228e-02,
        -1.29426820e-02, -8.63248482e-02,  8.53665452e-03,
         6.03761636e-02,  1.51121700e-02, -1.19132452e-01,
         1.15234498e-02,  5.97089268e-02, -3.93345915e-02,
         1.55673930e-02,  1.04602408e-02, -4.72456142e-02,
        -2.59243678e-02,  9.98532306e-03,  3.07146497e-02,
        -7.14843199e-02,  6.98962156e-03, -1.55133391e-02,
         2.18864493e-02, -2.78146137e-02,  6.92733750e-02,
        -2.75904182e-02,  2.62429249e-02,  3.52562703e-02,
        -4.26419154e-02,  7.46278442e-04,  6.59866631e-02,
        -5.15105315e-02, -3.58434394e-02, -6.53440552e-03,
        -2.75858082e-02, -1.00125626e-01,  7.83325210e-02,
        -1.45798819e-02, -6.18457392e-08,  2.00325269e-02,
         6.59785271e-02, -2.04702448e-02,  1.64044909e-02,
         7.63000920e-02,  7.32182711e-02,  5.65789733e-03,
        -6.97747571e-04, -3.63795902e-03,  6.02394231e-02,
        -3.27187479e-02, -6.45838380e-02, -5.97952381e-02,
        -1.76696498e-02,  6.10150350e-03, -5.63484663e-03,
        -1.22972175e-01,  6.35818765e-02, -2.19432507e-02,
        -1.16406530e-01,  2.34364923e-02, -7.23524690e-02,
         2.31774077e-02, -6.55987337e-02, -7.42682219e-02,
         2.60146316e-02,  3.59756835e-02,  7.68432915e-02,
        -3.08056902e-02, -2.34793257e-02, -6.30425215e-02,
        -3.62158343e-02, -1.03560602e-02, -4.75602522e-02,
        -2.87521686e-02,  2.96401195e-02, -5.26904454e-03,
         5.67889847e-02, -3.74489278e-03,  3.09611764e-02,
         3.48227732e-02,  3.78607474e-02,  2.10155863e-02,
         2.70692110e-02,  5.25520705e-02,  7.16230050e-02,
        -5.53751038e-03,  4.01093848e-02,  5.16276695e-02,
        -2.67314650e-02,  5.94224297e-02, -4.29224409e-02,
        -1.19761173e-02,  3.05985492e-02, -7.40331411e-02,
         1.84221026e-02, -8.64863396e-03, -8.83558095e-02,
        -5.91984019e-02, -1.00842532e-04,  1.12913661e-01,
         4.57790261e-03, -4.25971895e-02,  3.22623784e-03],
       [ 8.04571435e-03, -3.57392244e-02,  4.93873283e-02,
        -7.19191274e-03,  6.17601327e-04, -9.05684605e-02,
         5.75595349e-02, -4.39445637e-02,  1.74751244e-02,
         5.21203168e-02, -4.62332293e-02,  2.49039512e-02,
         4.80810739e-02,  6.86636567e-02,  3.56147103e-02,
         3.00088599e-02,  2.61450484e-02, -9.05241743e-02,
        -8.02173838e-02,  5.04851192e-02, -7.90870860e-02,
        -1.76848914e-03, -2.48927623e-02,  9.02153403e-02,
         5.83691383e-03, -6.91070929e-02, -6.67965487e-02,
        -6.99113822e-03, -1.04566000e-01, -2.66474038e-02,
         3.05640306e-02,  2.02933811e-02,  2.25454085e-02,
        -4.22677817e-03,  1.11172507e-02,  6.78260848e-02,
         1.06073366e-02,  7.56635964e-02, -8.22778046e-02,
         8.45728163e-03, -6.97611570e-02, -4.21974808e-02,
        -1.05675152e-02,  2.23673470e-02,  5.64496666e-02,
         8.16498883e-03,  1.09344028e-01,  3.16565335e-02,
        -1.76923815e-02, -3.21071856e-02, -3.39975767e-02,
        -4.91786923e-04,  3.72878276e-03,  2.83771660e-02,
        -1.28521193e-02, -1.07935071e-03, -6.32418394e-02,
         6.89900890e-02,  1.77270155e-02, -5.20958900e-02,
         8.28311220e-03,  5.45032471e-02, -5.42099513e-02,
        -4.53332514e-02, -4.07493673e-02, -2.82698348e-02,
         1.23605952e-02, -2.13816501e-02, -2.36266311e-02,
         1.25317900e-02, -2.37170346e-02,  3.97411659e-02,
        -1.24362200e-01,  7.60625973e-02,  5.50833605e-02,
         8.28217193e-02,  2.97119375e-02, -1.84067711e-02,
        -1.96195040e-02,  5.54319210e-02, -3.49144340e-02,
        -4.14677560e-02, -3.37047391e-02,  7.31324926e-02,
         4.41837087e-02,  2.55246330e-02, -8.26406199e-03,
        -1.07323211e-02, -4.26243730e-02, -2.84964149e-03,
         7.38558918e-02,  2.27768552e-02,  7.15425762e-04,
         4.36012670e-02,  5.09079918e-02,  6.38482422e-02,
        -2.73155421e-02, -6.55021667e-02, -7.69265145e-02,
         3.55171636e-02,  9.60494503e-02,  2.18195673e-02,
         1.20155085e-02, -1.17863519e-02, -4.57931729e-03,
        -8.58036242e-03,  3.37150581e-02,  2.31918581e-02,
        -7.58325830e-02, -5.23878597e-02,  4.53933515e-02,
        -3.80785875e-02, -3.34904753e-02,  9.20352861e-02,
         2.87689175e-02, -3.33817676e-02, -1.95851224e-03,
        -3.04574991e-04, -1.70499664e-02,  2.85335500e-02,
        -8.81096125e-02, -4.02252525e-02, -4.00092639e-02,
        -1.03192739e-02, -2.51968186e-02,  2.14093160e-02,
         1.31045297e-01, -5.29635556e-34, -1.09651744e-01,
         1.29811605e-02,  5.92654757e-03,  4.73506488e-02,
        -8.60290788e-03, -3.67089249e-02,  3.05214748e-02,
         5.53066619e-02, -4.71984968e-02, -1.25118969e-02,
        -1.15366459e-01,  9.08003561e-03,  1.07346557e-01,
        -4.94735166e-02, -1.34290578e-02, -4.61562946e-02,
         2.45320108e-02,  9.45081376e-03,  2.04324275e-02,
        -3.99918258e-02, -4.67826203e-02,  2.21171305e-02,
        -4.58187126e-02, -8.13270174e-03, -7.65664317e-03,
         1.92284007e-02,  4.85844314e-02, -2.55902447e-02,
         1.61541766e-03, -1.37180518e-02,  9.67307854e-03,
         7.36415340e-03,  1.14088180e-02,  1.28853455e-01,
         7.71834049e-03,  7.06362128e-02,  2.54451782e-02,
         4.06523719e-02,  2.44039148e-02,  1.43776638e-02,
        -6.00932389e-02,  7.38180950e-02, -2.44701412e-02,
         8.98901969e-02,  3.17048165e-03,  1.01834446e-01,
         4.17741574e-02, -5.95178045e-02, -3.23182493e-02,
         3.80938537e-02,  1.21155586e-02, -4.07834202e-02,
         2.84823496e-02,  4.90988195e-02, -9.35704820e-03,
         6.50073960e-02,  7.23532587e-02, -1.67793557e-02,
        -8.22416879e-03, -1.61572993e-02,  5.96225597e-02,
        -3.36083882e-02,  2.12108120e-02, -6.06091283e-02,
         1.54377654e-01, -7.24145994e-02, -3.77272144e-02,
        -3.26890238e-02, -1.80383853e-03, -1.01959873e-02,
        -1.60680851e-03, -6.91846311e-02,  8.28444958e-02,
         9.88839939e-02,  3.45471827e-03, -9.90247279e-02,
        -3.52827199e-02, -7.13178888e-02, -4.96000424e-02,
        -3.43954898e-02, -8.13041851e-02,  4.81447354e-02,
         5.00680553e-03, -2.21499279e-02, -5.60057089e-02,
         1.00068180e-02, -3.59794125e-02,  1.06184304e-01,
        -4.54196781e-02,  7.16393366e-02, -2.36773286e-02,
         9.98144876e-03,  2.73602754e-02,  1.05985418e-01,
         4.60164621e-02,  9.59028811e-34, -1.12306982e-01,
         2.78912503e-02, -3.35900933e-02,  5.39242513e-02,
        -2.22290792e-02,  1.53769003e-02,  3.10411118e-02,
         3.39010470e-02,  7.43166879e-02,  3.42470892e-02,
        -3.35058663e-03, -2.05351152e-02, -3.62369828e-02,
         2.29334272e-02, -3.01991813e-02, -1.00819916e-01,
         3.29194479e-02,  6.77542537e-02,  1.35644851e-02,
        -5.20551018e-03, -6.58158809e-02,  9.54550803e-02,
        -1.34039167e-02,  1.53884888e-02, -7.22936317e-02,
         9.67836380e-02, -8.08119774e-02, -4.53450298e-03,
        -6.42011613e-02, -4.99278493e-02,  4.64197434e-02,
         2.21340638e-02,  3.13109830e-02,  9.13568884e-02,
        -4.61120084e-02, -1.02761097e-01,  3.04415412e-02,
         5.09875938e-02,  6.70140833e-02,  1.04042664e-02,
         1.63534116e-02,  3.92031036e-02,  2.17154529e-02,
         5.36604039e-02,  3.62809859e-02, -4.22140285e-02,
        -2.47227512e-02,  1.90311894e-02,  3.61723788e-02,
         6.37021437e-02, -3.21587035e-03, -8.50392785e-03,
         3.94655652e-02,  9.02653858e-03,  1.93095598e-02,
         6.60718530e-02,  1.02695031e-02, -4.43853736e-02,
        -1.56523231e-02, -1.55713819e-02,  1.32904593e-02,
        -1.16108665e-02,  4.21831720e-02, -5.44776656e-02,
         1.29237205e-01, -2.25757826e-02,  5.26204295e-02,
        -1.58437248e-02,  9.33165401e-02,  6.38017012e-03,
        -9.36162379e-03, -6.08875453e-02, -3.27308178e-02,
        -3.44816931e-02,  3.29974256e-02, -4.79391851e-02,
        -9.81301218e-02,  2.91165207e-02, -2.70903204e-02,
         1.81867145e-02, -1.73860621e-02, -4.40371595e-02,
        -7.97002017e-02,  3.01647168e-02, -6.35260642e-02,
         1.25963185e-02,  8.50250348e-02, -4.58910689e-02,
         5.81017435e-02, -2.71002967e-02,  8.42775777e-02,
        -4.09972668e-02, -3.37656662e-02,  1.02088610e-02,
        -2.54193339e-02, -1.40610261e-08,  4.94446829e-02,
        -9.04356316e-02, -6.06710128e-02,  8.29529613e-02,
        -3.29032317e-02,  4.14911099e-02,  9.99588706e-03,
         6.96135871e-03,  3.99235310e-03, -3.24332975e-02,
        -3.14656794e-02, -5.33161424e-02, -3.80912982e-02,
         1.62076950e-02,  2.45778617e-02, -7.26419464e-02,
        -6.56893998e-02, -8.23131725e-02, -8.00501183e-02,
        -5.36649153e-02,  5.60894683e-02, -1.10913347e-02,
         9.62170248e-04, -1.22690305e-01, -5.13837002e-02,
         9.96699184e-03,  1.00696124e-02,  1.07073054e-01,
         1.19758239e-02,  1.00423349e-02, -6.28261715e-02,
        -7.49696791e-02, -6.34072581e-03, -2.72201188e-02,
        -1.28096133e-01, -2.62460317e-02, -1.81464553e-02,
        -9.85359848e-02, -3.02990489e-02, -4.02614772e-02,
         9.94291157e-02,  5.35999462e-02,  2.74899434e-02,
        -5.53677836e-03,  8.43571275e-02,  8.35161880e-02,
         3.74304689e-02,  7.11937919e-02,  2.98903249e-02,
         2.32728496e-02, -3.62112783e-02,  6.20540194e-02,
         2.15147790e-02,  5.19732460e-02,  1.45338112e-02,
        -4.60966639e-02,  5.02554253e-02, -7.27027655e-02,
         2.92778704e-02,  5.62662967e-02, -3.86355072e-02,
         1.53831402e-02, -6.23094998e-02, -2.77466811e-02]], dtype=float32)

In [32]:
filtered_embeddings.shape

(1903, 384)

In [34]:
len(filtered_embeddings)

1903

In [35]:
X = filtered_embeddings
y = df_non_legacy['target_label'].values

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
clf = LogisticRegression(max_iter=1000)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
report = classification_report(y_test, y_pred)
print(report)

                precision    recall  f1-score   support

Critical Error       0.91      1.00      0.95        48
         Error       0.98      0.89      0.93        47
   HTTP Status       1.00      1.00      1.00       304
Resource Usage       1.00      1.00      1.00        49
Security Alert       1.00      0.99      1.00       123

      accuracy                           0.99       571
     macro avg       0.98      0.98      0.98       571
  weighted avg       0.99      0.99      0.99       571

In [37]:
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.989492119089317

In [42]:
import joblib
joblib.dump(clf, '../models/log_classifier.joblib')

['../models/log_classifier.joblib']